"""PostgreSQL backend that the app can use through its existing sqlite3 calls.

WHY THIS EXISTS
===============
The trading engine (paper_trading_app_TV.py) is deliberately frozen: it is the
audited money-handling code. Every one of its SQL calls is written for sqlite3.
Rather than rewrite that file for a hosted database, this module is a DB-API
2.0 shim that *is* `sqlite3` as far as the app is concerned, but speaks
PostgreSQL underneath:

    import pg_compat
    pg_compat.install()      # only when PAPER_TRADER_DB_URL is set
    import sqlite3           # <- now this is the shim

`install()` rebinds sys.modules["sqlite3"], so every later `import sqlite3`
(the frozen engine, engine.py, accounts.py, app_web.py) gets the shim without
a single edit to any of them. With no PAPER_TRADER_DB_URL set, nothing here is
imported and the app keeps using real SQLite exactly as before.

WHAT IT TRANSLATES (measured from the actual code, not guessed)
==============================================================
  ? placeholders           -> %s, skipping 'literals' and -- /* comments */
  literal % in SQL         -> %% when parameters are present (psycopg2 rule)
  PRAGMA foreign_keys=ON   -> ignored: PostgreSQL enforces FKs natively
  PRAGMA journal_mode=WAL  -> ignored (with synchronous/busy_timeout)
  PRAGMA table_info(t)     -> emulated from information_schema, same columns
  INSERT OR REPLACE        -> INSERT ... ON CONFLICT (pk) DO UPDATE
  cursor.lastrowid         -> appends RETURNING id to the INSERT
  INTEGER PRIMARY KEY AUTOINCREMENT -> ... GENERATED BY DEFAULT AS IDENTITY
  REAL                     -> DOUBLE PRECISION (DDL only)
  COLLATE NOCASE           -> lower(...) in queries, dropped in DDL
  sqlite3.Error & friends  -> mapped from psycopg2's exception classes

It also survives the thing that actually breaks long-lived hosted databases:
a dropped or suspended connection. Reads and the first statement of a
connection are retried once on a fresh connection; a connection with
uncommitted writes is never silently retried, so a statement cannot be
applied twice.
"""

from __future__ import annotations

import os
import re
import sys
import threading
import time

__all__ = ["install", "connect", "Error", "DatabaseError", "IntegrityError",
           "OperationalError", "ProgrammingError", "InterfaceError",
           "NotSupportedError", "Row", "translate", "set_driver",
           "is_installed", "URL_ENV_VARS"]

# A hosted URL may come from either name: DATABASE_URL is the convention the
# platforms themselves use (Render, Neon, Railway, Heroku).
URL_ENV_VARS = ("PAPER_TRADER_DB_URL", "DATABASE_URL")

SCHEME = ("postgres://", "postgresql://")


# ---------------------------------------------------------------------------
# sqlite3's exception tree, so `except sqlite3.IntegrityError` keeps working
# ---------------------------------------------------------------------------
class Error(Exception):
    """Base class, mirroring sqlite3.Error."""


class InterfaceError(Error):
    pass


class DatabaseError(Error):
    pass


class DataError(DatabaseError):
    pass


class OperationalError(DatabaseError):
    pass


class IntegrityError(DatabaseError):
    pass


class InternalError(DatabaseError):
    pass


class ProgrammingError(DatabaseError):
    pass


class NotSupportedError(DatabaseError):
    pass


class Row(tuple):
    """Minimal stand-in for sqlite3.Row (the app indexes rows positionally,
    so this exists only so nothing explodes if some future code asks for it)."""

    def __new__(cls, values, keys=None):
        obj = super().__new__(cls, values)
        obj._keys = list(keys or [])
        return obj

    def keys(self):
        return list(self._keys)

    def __getitem__(self, item):
        if isinstance(item, str):
            return tuple.__getitem__(self, self._keys.index(item))
        return tuple.__getitem__(self, item)

    def get(self, key, default=None):
        try:
            return self[key]
        except (ValueError, IndexError):
            return default


def _driver():
    """psycopg2, imported on demand so unit tests can substitute a fake."""
    if _DRIVER is not None:
        return _DRIVER
    try:
        import psycopg2                                    # noqa: PLC0415
        import psycopg2.extensions                          # noqa: PLC0415
    except ImportError as exc:                              # pragma: no cover
        raise InterfaceError(
            "PostgreSQL backend selected (PAPER_TRADER_DB_URL is set) but "
            "psycopg2 is not installed. Run: pip install psycopg2-binary"
        ) from exc
    return psycopg2


_DRIVER = None


def set_driver(module):
    """Test hook: use this object as the psycopg2 stand-in."""
    global _DRIVER
    _DRIVER = module


# ---------------------------------------------------------------------------
# SQL translation
# ---------------------------------------------------------------------------
_AUTOINC = re.compile(r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b", re.I)
_AUTOINC_LOOSE = re.compile(r"\bAUTOINCREMENT\b", re.I)
_REAL_TYPE = re.compile(r"\bREAL\b", re.I)
_NOCASE = re.compile(r"(\?|%s|\w+(?:\.\w+)?)\s+COLLATE\s+NOCASE", re.I)
_NOCASE_PLAIN = re.compile(r"\s+COLLATE\s+NOCASE", re.I)
_TABLE_INFO = re.compile(
    r"PRAGMA\s+table_info\s*\(\s*['\"]?([A-Za-z_][A-Za-z0-9_]*)['\"]?\s*\)",
    re.I)
_PRAGMA = re.compile(r"^\s*PRAGMA\b", re.I)
_DDL = re.compile(r"^\s*(CREATE|ALTER|DROP)\b", re.I)
_INSERT_REPLACE = re.compile(
    r"^\s*INSERT\s+OR\s+REPLACE\s+INTO\s+([A-Za-z_][A-Za-z0-9_]*)\s*"
    r"\(([^)]*)\)\s*VALUES\s*\((.*)\)\s*$", re.I | re.S)
_INSERT = re.compile(
    r"^\s*INSERT\s+INTO\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(([^)]*)\)\s*VALUES\b",
    re.I)
_RETURNING = re.compile(r"\bRETURNING\b", re.I)
_PRAGMA_JOURNAL = re.compile(r"PRAGMA\s+journal_mode", re.I)


def _scan(sql, escape_percent=False):
    """Walks SQL outside of literals and comments, in one pass.

    - '?' becomes '%s', PostgreSQL's placeholder. The '%s' this function emits
      is never re-escaped.
    - when parameters are present, a literal '%' becomes '%%' first, because
      psycopg2 %-interpolates the whole statement (the classic psycopg2 trap).

    Inside single-quoted strings, double-quoted identifiers and comments a '?'
    is literal text, not a parameter marker - translating it would corrupt the
    query. Returns (out_text, placeholders_seen).
    """
    out = []
    i = 0
    n = len(sql)
    seen = 0
    while i < n:
        ch = sql[i]
        if ch == "'" or ch == '"':
            quote = ch
            out.append(ch)
            i += 1
            while i < n:
                c = sql[i]
                if c == "%" and escape_percent:
                    out.append("%%")
                    i += 1
                    continue
                out.append(c)
                if c == quote:
                    if i + 1 < n and sql[i + 1] == quote:   # '' escape
                        out.append(sql[i + 1])
                        i += 2
                        continue
                    i += 1
                    break
                i += 1
            continue
        if ch == "-" and sql.startswith("--", i):
            end = sql.find("\n", i)
            end = n if end < 0 else end
            chunk = sql[i:end]
            out.append(chunk.replace("%", "%%") if escape_percent else chunk)
            i = end
            continue
        if ch == "/" and sql.startswith("/*", i):
            end = sql.find("*/", i + 2)
            end = n if end < 0 else end + 2
            chunk = sql[i:end]
            out.append(chunk.replace("%", "%%") if escape_percent else chunk)
            i = end
            continue
        if ch == "?":
            out.append("%s")
            seen += 1
            i += 1
            continue
        if ch == "%" and escape_percent:
            out.append("%%")
            i += 1
            continue
        out.append(ch)
        i += 1
    return "".join(out), seen


class Statement:
    """A translated statement plus what the cursor must do about it."""

    __slots__ = ("kind", "sql", "table", "columns", "params", "note")

    def __init__(self, kind, sql, table=None, columns=None, params=None,
                 note=""):
        self.kind = kind          # select|write|ddl|table_info|noop|replace
        self.sql = sql
        self.table = table
        self.columns = columns or []
        self.params = params
        self.note = note

    def __repr__(self):                                     # pragma: no cover
        return f"Statement({self.kind!r}, {self.sql!r}, table={self.table!r})"


# ---------------------------------------------------------------------------
# SQLite's two-argument scalar MAX() / MIN()
# ---------------------------------------------------------------------------
# SQLite defines MAX(a, b) and MIN(a, b) as scalar functions that return the
# larger / smaller argument. PostgreSQL has no such function: there MAX and MIN
# are aggregates only, and the scalar form is spelled GREATEST() / LEAST(). So
# `MAX(COALESCE(stop_loss, ?), ?)` fails on Postgres with
#     function max(numeric, numeric) does not exist
# That exact statement is how a Trading Mode entry records its protective stop,
# in both engine.py and paper_trading_app_TV.py. Because the failure was being
# swallowed by a bare `except sqlite3.Error: return False`, every hosted entry
# silently failed to book while every scan and recommendation looked healthy.
_SCALAR_FUNC = re.compile(r"\b(MAX|MIN)\s*\(", re.I)


def _scalar_maxmin(sql):
    """Two-argument MAX()/MIN() -> GREATEST()/LEAST(); aggregates untouched."""
    out = []
    i = 0
    while i < len(sql):
        match = _SCALAR_FUNC.search(sql, i)
        if not match:
            out.append(sql[i:])
            break
        out.append(sql[i:match.end()])
        start = match.end()                  # just past the opening paren
        depth, comma, j = 1, False, start
        while j < len(sql) and depth:
            ch = sql[j]
            if ch == "(":
                depth += 1
            elif ch == ")":
                depth -= 1
                if not depth:
                    break
            elif ch == "," and depth == 1:
                comma = True
            j += 1
        if depth or not comma:               # single argument: an aggregate
            i = match.end()
            continue
        name = "GREATEST" if match.group(1).upper() == "MAX" else "LEAST"
        out[-1] = sql[i:match.start()] + name + "("
        out.append(sql[start:j] + ")")
        i = j + 1
    return "".join(out)


def translate(sql, params=None):
    """Pure translation: no database access, so it is unit-testable."""
    if not isinstance(sql, str):
        raise ProgrammingError("SQL statement must be a string")

    match = _TABLE_INFO.search(sql)
    if match:
        return Statement("table_info", sql, table=match.group(1),
                         params=[])

    if _PRAGMA.match(sql):
        if _PRAGMA_JOURNAL.search(sql):
            # Callers only care that it did not raise; report "delete" politely.
            return Statement("noop", sql, params=[], note="delete")
        return Statement("noop", sql, params=[])

    if _DDL.match(sql):
        text = _AUTOINC.sub(
            "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", sql)
        text = _AUTOINC_LOOSE.sub("", text)
        if re.match(r"^\s*CREATE\s+TABLE", text, re.I):
            text = _REAL_TYPE.sub("DOUBLE PRECISION", text)
        text = _NOCASE_PLAIN.sub("", text)
        return Statement("ddl", text, params=params)

    # COLLATE NOCASE binds tighter than '=', so `email = ? COLLATE NOCASE`
    # means a case-insensitive comparison. lower(...) is the portable form.
    nocase = _scalar_maxmin(_NOCASE.sub(r"lower(\1)", sql))
    text, seen = _scan(nocase, escape_percent=params is not None)
    if params is not None and seen == 0:
        # Parameters with no placeholder: they will not be interpolated, so a
        # literal % must stay single.
        text, seen = _scan(nocase, escape_percent=False)

    replace = _INSERT_REPLACE.match(text)
    if replace:
        table = replace.group(1)
        columns = [c.strip().strip('"') for c in replace.group(2).split(",")]
        return Statement("replace", text, table=table, columns=columns,
                         params=params)

    insert = _INSERT.match(text)
    if insert:
        return Statement("write", text, table=insert.group(1), params=params)

    kind = "select" if re.match(r"^\s*(SELECT|WITH|VALUES|SHOW)\b", text, re.I) \
        else "write"
    return Statement(kind, text, params=params)


# ---------------------------------------------------------------------------
# Emulated PRAGMA table_info, in sqlite3's exact column order
# ---------------------------------------------------------------------------
TABLE_INFO_SQL = """
SELECT c.ordinal_position - 1                       AS cid,
       c.column_name,
       CASE
         WHEN c.data_type IN ('integer', 'bigint', 'smallint') THEN 'INTEGER'
         WHEN c.data_type IN ('double precision', 'real', 'numeric') THEN 'REAL'
         WHEN c.data_type = 'boolean' THEN 'INTEGER'
         ELSE 'TEXT'
       END                                          AS type,
       CASE WHEN c.is_nullable = 'NO' THEN 1 ELSE 0 END AS notnull,
       c.column_default                             AS dflt_value,
       CASE WHEN pk.column_name IS NOT NULL THEN 1 ELSE 0 END AS pk
  FROM information_schema.columns c
  LEFT JOIN (
        SELECT kcu.column_name
          FROM information_schema.table_constraints tc
          JOIN information_schema.key_column_usage kcu
            ON kcu.constraint_name = tc.constraint_name
           AND kcu.table_schema = tc.table_schema
         WHERE tc.constraint_type = 'PRIMARY KEY'
           AND tc.table_name = %s
       ) pk ON pk.column_name = c.column_name
 WHERE c.table_name = %s
 ORDER BY c.ordinal_position
"""

TABLE_PK_SQL = """
SELECT kcu.column_name
  FROM information_schema.table_constraints tc
  JOIN information_schema.key_column_usage kcu
    ON kcu.constraint_name = tc.constraint_name
   AND kcu.table_schema = tc.table_schema
 WHERE tc.constraint_type = 'PRIMARY KEY'
   AND tc.table_name = %s
 ORDER BY kcu.ordinal_position
"""

HAS_COLUMN_SQL = """
SELECT 1 FROM information_schema.columns
 WHERE table_name = %s AND column_name = %s
"""


# ---------------------------------------------------------------------------
# Connection / cursor
# ---------------------------------------------------------------------------
class Cursor:
    def __init__(self, conn):
        self._conn = conn
        self._cur = conn._conn.cursor()
        self._noop_rows = []
        self.lastrowid = None
        self.rowcount = -1
        self.description = None
        self.arraysize = 1
        self._closed = False

    # -- internals ---------------------------------------------------------
    def _run(self, statement, params):
        sql = statement.sql
        if statement.kind == "table_info":
            self._cur.execute(TABLE_INFO_SQL,
                              (statement.table, statement.table))
            return
        if statement.kind == "noop":
            # PostgreSQL always writes WAL and enforces foreign keys; only the
            # caller's expectation of a row needs satisfying.
            self._noop_rows = [("wal",)] if statement.note == "delete" else []
            self.description = [("journal_mode",)]
            self.rowcount = 0
            return
        if statement.kind == "replace":
            sql = self._replace_sql(statement)
        elif statement.kind == "write":
            sql = self._maybe_returning(statement)
        if params is None:
            self._cur.execute(sql)
        else:
            self._cur.execute(sql, params)
        self.rowcount = self._cur.rowcount
        self.description = self._cur.description
        if statement.kind == "write" and self.description:
            row = self._cur.fetchone()
            self.lastrowid = row[0] if row else None
            self.description = None
            if self.rowcount in (-1, None):
                self.rowcount = 1

    def _replace_sql(self, statement):
        """INSERT OR REPLACE -> INSERT ... ON CONFLICT (pk) DO UPDATE."""
        pks = self._conn._primary_key(statement.table)
        if not pks:
            raise NotSupportedError(
                f"INSERT OR REPLACE needs a primary key; "
                f"table {statement.table!r} has none")
        cols = statement.columns
        target = ", ".join(pks)
        updatable = [c for c in cols if c not in pks]
        if updatable:
            assignments = ", ".join(f"{c} = EXCLUDED.{c}" for c in updatable)
            tail = f" ON CONFLICT ({target}) DO UPDATE SET {assignments}"
        else:
            tail = f" ON CONFLICT ({target}) DO NOTHING"
        return statement.sql + tail

    def _maybe_returning(self, statement):
        """cursor.lastrowid is emulated with RETURNING id, when the table has
        one. Tables keyed on something else (settings, risk_state) get nothing,
        exactly like SQLite, where lastrowid would also be meaningless."""
        if _RETURNING.search(statement.sql):
            return statement.sql
        if not self._conn._has_column(statement.table, "id"):
            return statement.sql
        return statement.sql + " RETURNING id"

    # -- DB-API ------------------------------------------------------------
    def execute(self, sql, params=None):
        statement = translate(sql, params)
        if statement.params is None:
            statement.params = params
        was_dirty = self._conn._dirty
        self._conn._note_write(statement.kind)
        try:
            self._run(statement, statement.params)
        except Exception as exc:                            # noqa: BLE001
            mapped = _map_exc(exc)
            # A hosted database drops idle connections (Neon suspends after a
            # few minutes). Retry once on a fresh connection - but only when
            # nothing is pending, so a statement can never be applied twice.
            safe = statement.kind in ("select", "table_info", "noop") \
                or not was_dirty
            if isinstance(mapped, OperationalError) and safe \
                    and _retryable(exc):
                try:
                    self._conn._reconnect()
                    self._cur = self._conn._conn.cursor()
                    self._run(statement, statement.params)
                    return self
                except Exception as retry_exc:              # noqa: BLE001
                    raise _map_exc(retry_exc) from retry_exc
            raise mapped from exc
        return self

    def executemany(self, sql, seq_of_params):
        for params in seq_of_params:
            self.execute(sql, params)
        return self

    def executescript(self, script):
        for part in filter(None, (s.strip() for s in script.split(";"))):
            self.execute(part)
        return self

    def fetchone(self):
        if self._noop_rows:
            return self._noop_rows[0]
        if self._cur.description is None:
            return None
        return self._cur.fetchone()

    def fetchmany(self, size=None):
        if self._noop_rows:
            rows, self._noop_rows = self._noop_rows, []
            return rows
        if self._cur.description is None:
            return []
        return self._cur.fetchmany(size or self.arraysize)

    def fetchall(self):
        if self._noop_rows:
            rows, self._noop_rows = self._noop_rows, []
            return rows
        if self._cur.description is None:
            return []
        return self._cur.fetchall()

    def close(self):
        if not self._closed:
            self._closed = True
            try:
                self._cur.close()
            except Exception:                               # noqa: BLE001
                pass

    def __iter__(self):
        return iter(self.fetchall())


class Connection:
    def __init__(self, dsn, timeout=10, kwargs=None):
        self._dsn = dsn
        self._lock = threading.RLock()
        self._pk_cache = {}
        self._col_cache = {}
        self._dirty = False
        self._closed = False
        self._connect(timeout, kwargs or {})

    # -- internals ---------------------------------------------------------
    def _connect(self, timeout, kwargs):
        driver = _driver()
        params = dict(kwargs)
        params.setdefault("connect_timeout", max(1, int(timeout or 10)))
        params.setdefault("application_name", "paper-trader")
        last = None
        for attempt, delay in enumerate((0.0, 0.5, 1.5, 3.0)):
            if delay:
                time.sleep(delay)
            try:
                self._conn = driver.connect(self._dsn, **params)
                self._dirty = False
                return
            except Exception as exc:                        # noqa: BLE001
                last = exc
                if not _retryable(exc) or attempt == 3:
                    break
        raise _map_exc(last)

    def _reconnect(self, timeout=10):
        try:
            self._conn.close()
        except Exception:                                   # noqa: BLE001
            pass
        self._connect(timeout, {})

    def _primary_key(self, table):
        if table not in self._pk_cache:
            cur = self._conn.cursor()
            cur.execute(TABLE_PK_SQL, (table,))
            self._pk_cache[table] = [r[0] for r in cur.fetchall()]
            cur.close()
        return self._pk_cache[table]

    def _has_column(self, table, column):
        key = (table, column)
        if key not in self._col_cache:
            cur = self._conn.cursor()
            cur.execute(HAS_COLUMN_SQL, (table, column))
            self._col_cache[key] = cur.fetchone() is not None
            cur.close()
        return self._col_cache[key]

    def _note_write(self, kind):
        if kind in ("write", "replace", "ddl"):
            self._dirty = True

    # -- DB-API ------------------------------------------------------------
    def cursor(self):
        return Cursor(self)

    def execute(self, sql, params=None):
        return self.cursor().execute(sql, params)

    def executemany(self, sql, seq_of_params):
        return self.cursor().executemany(sql, seq_of_params)

    def executescript(self, script):
        return self.cursor().executescript(script)

    def commit(self):
        self._conn.commit()
        self._dirty = False

    def rollback(self):
        self._conn.rollback()
        self._dirty = False

    def close(self):
        if self._closed:
            return
        self._closed = True
        try:
            if self._dirty:
                self._conn.rollback()
        except Exception:                                   # noqa: BLE001
            pass
        try:
            self._conn.close()
        except Exception:                                   # noqa: BLE001
            pass

    # psycopg2-style aliases, harmless to provide
    def set_session(self, **kwargs):                        # pragma: no cover
        return None

    @property
    def autocommit(self):
        return False

    def __enter__(self):
        return self

    def __exit__(self, *exc_info):
        if exc_info and exc_info[0]:
            self.rollback()
        else:
            self.commit()


# ---------------------------------------------------------------------------
# exception mapping
# ---------------------------------------------------------------------------
def _map_exc(exc):
    if isinstance(exc, Error):
        return exc
    driver = _DRIVER
    if driver is not None:
        table = (
            (getattr(driver, "IntegrityError", None), IntegrityError),
            (getattr(driver, "OperationalError", None), OperationalError),
            (getattr(driver, "InterfaceError", None), InterfaceError),
            (getattr(driver, "ProgrammingError", None), ProgrammingError),
            (getattr(driver, "DataError", None), DataError),
            (getattr(driver, "InternalError", None), InternalError),
            (getattr(driver, "NotSupportedError", None), NotSupportedError),
            (getattr(driver, "DatabaseError", None), DatabaseError),
            (getattr(driver, "Error", None), Error),
        )
        for source, target in table:
            if source is not None and isinstance(exc, source):
                return target(str(exc).strip())
    return OperationalError(str(exc).strip())


_RETRY_HINTS = (
    "server closed the connection",
    "connection already closed",
    "connection has been closed",
    "terminating connection",
    "could not connect",
    "connection refused",
    "connection reset",
    "timeout expired",
    "the database system is starting up",
    "ssl connection has been closed",
)


def _retryable(exc):
    text = str(exc).lower()
    return any(hint in text for hint in _RETRY_HINTS)


# ---------------------------------------------------------------------------
# public entry points
# ---------------------------------------------------------------------------
def resolve_url():
    for name in URL_ENV_VARS:
        value = (os.environ.get(name) or "").strip()
        if value:
            return value
    return ""


def connect(database=None, timeout=10, **kwargs):
    """Same signature as sqlite3.connect; `database` is ignored on purpose.

    The frozen engine calls sqlite3.connect(DB_FILE, timeout=10). Which file
    it thinks it is opening no longer matters: the URL decides.
    """
    url = resolve_url()
    if not url:
        raise InterfaceError(
            "pg_compat is active but no database URL is set. Define "
            + " or ".join(URL_ENV_VARS) + " (a postgres:// connection string).")
    return Connection(url, timeout=timeout, kwargs=kwargs)


_INSTALLED = False


def install(verbose=True):
    """Rebinds `sqlite3` to this module for the rest of the process."""
    global _INSTALLED
    if _INSTALLED:
        return True
    sys.modules["sqlite3"] = sys.modules[__name__]
    _INSTALLED = True
    if verbose:
        url = resolve_url()
        host = re.sub(r"://[^@]*@", "://***@", url)
        print(f"  Database : PostgreSQL via pg_compat  ({host})")
    return True


def is_installed():
    return _INSTALLED


def auto_install(verbose=True):
    """Installs only when a PostgreSQL URL is configured."""
    url = resolve_url()
    if url.startswith(SCHEME) or (url and "://" in url
                                  and not url.startswith("sqlite")):
        return install(verbose=verbose)
    return False
